### ISSUE TITLE
Allow outputTemplate to be editable or configurable

### ISSUE THREAD

**Issue by andrewheiss** [zerok/remarked#2]
Hello! 

First of all, thanks for such a fantastic, easy to use script. I've been looking all over for an easy way to broadcast a remarked.js presentation and this is the best.

It would be fantastic if the HTML template that remarked inserts `markdownFile` into could be configurable somehow. The [xaringan](https://github.com/yihui/xaringan) library, for example, lets you build remark slideshows with R, but it inserts several additional pieces of HTML into its templates (like extra `<script>` tags to enable FontAwesome and MathJax). See [here for an example presentation](https://slides.yihui.name/xaringan/#1).

For now, my solution is to fork the remarked project, edit the `outputTemplate` variable in `cmd/remarked/main.go`, and recompile the binary, which works, but it's not flexible at all.

Would there be a way to make this more user configurable?

Thanks!

**Comment by zerok** [comment]
Hi :)

Thank you for your kind words! Weirdly enough, I had that somehow on my roadmap for remarked but completely forgot about it. I was thinking about keeping the default as is an additionally allow that to be overridden with a path specified inside the configuration file. Would that work for your case?

**Comment by andrewheiss** [comment]
Yep, that would be fantastic! (and a lot easier than forking Go projects, which is [way more complicated](https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md#cloning-a-fork) than I had anticipated)

**Comment by zerok** [comment]
Added in da69b78 😄

**Comment by andrewheiss** [comment]
Amazing, this is perfect, thanks!
